services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./volumes/portainer/portainer_data:/data
    environment:
      - PORTAINER_HTTP_ENABLED=true
    networks:
      - portainer_network
    command: --http-enabled
    labels:
      - "traefik.enable=false"

volumes:
  portainer_data:
    driver: local

networks:
  portainer_network:
    name: portainer_network
    driver: bridge
