# Load variables from .env file
# Create this file by copying src/.env-example to .env and modifying as needed

services:
  # InfluxDB server for development/testing
  influxdb:
    image: influxdb:1.8
    container_name: sysadmintoolkit-influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=metrics
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    volumes:
      - ./volumes/influxdb_data:/var/lib/influxdb
    profiles:
      - development
    networks:
      - backup_network

  # Backup service
  backup-service:
    container_name: sysadmintoolkit-backup-service
    build:
      context: .
      dockerfile: backup_influxdb.dockerfile
    # Environment variables are loaded from .env file
    # and can be overridden here if needed
    volumes:
      - ./backup_config.yaml:/app/backup_config.yaml
      - ./volumes/backup_logs:/var/log/backup_influxdb
    profiles:
      - development
      - production
    networks:
      - backup_network
    command: >
      sh -c "if grep -q 'backup_schedule:.*[^\"[:space:]]' /app/backup_config.yaml; then
               python /app/backup_influxdb_cron.py;
             else
               python /app/backup_influxdb.py;
             fi"

networks:
  backup_network:
    driver: bridge
    name: ${INFLUXDB_NETWORK:-influxdb_network}
