### Shared configuration for all services backup ###
x-sysadmintoolkit-backup-service: &sysadmintoolkit-backup-service
  build:
    context: .
    dockerfile: backup-influxdb.dockerfile
  volumes:
    - ./volumes/backup_logs:/var/log/backup_influxdb
  networks:
    - backup_network

### Services ###
services:
  sysadmintoolkit-influxdb: # InfluxDB server for development/testing
    image: influxdb:1.8
    container_name: sysadmintoolkit-influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=metrics
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    volumes:
      - ./volumes/influxdb_data:/var/lib/influxdb
    profiles:
      - development
    networks:
      - backup_network

  sysadmintoolkit-backup-service-dev: # Backup service for development
    container_name: sysadmintoolkit-backup-service-dev
    <<: *sysadmintoolkit-backup-service
    volumes:
      - ./volumes/backup_logs:/var/log/backup_influxdb
      - ./:/app/
    profiles:
      - development

  sysadmintoolkit-backup-service-prod: # Backup service for production
    container_name: sysadmintoolkit-backup-service-prod
    <<: *sysadmintoolkit-backup-service
    profiles:
      - production
    command: >
      sh -c "if grep -q 'backup_schedule:.*[^\"[:space:]]' /app/backup_config.yaml; then
               python /app/backup_influxdb_cron.py;
             else
               python /app/backup_influxdb.py;
             fi"

### Networks ###
networks:
  backup_network:
    driver: bridge
    name: ${INFLUXDB_NETWORK:-influxdb_network}
