{
 "title": "MonitoringHost",
 "tags": [ "linux" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Pressure",
   "type": "bargauge",
   "description": "\"Pressure\" se refiere al sistema de señal de presión de recursos (PSI, por sus siglas en inglés) que es parte del kernel de Linux. PSI proporciona información detallada sobre la presión de recursos en el sistema, incluyendo la presión de la CPU, la memoria y la E/S (entrada/salida).\n\n1. **Presión de la CPU (CPU Pressure)**: Esta métrica indica cuánto tiempo están pasando los procesos esperando para ejecutarse en la CPU debido a la falta de recursos de CPU disponibles. Una presión alta de la CPU puede indicar que hay demasiados procesos en cola esperando para ser ejecutados, lo que puede afectar el rendimiento general del sistema.\n    \n2. **Presión de memoria (Memory Pressure)**: Esta métrica muestra cuánto tiempo los procesos están esperando para acceder a la memoria debido a la falta de recursos de memoria disponibles. Una presión alta de memoria puede indicar que el sistema está utilizando la memoria de forma ineficiente o que hay una gran cantidad de procesos compitiendo por los mismos recursos de memoria.\n    \n3. **Presión de E/S (I/O Pressure)**: Esta métrica indica cuánto tiempo están esperando los procesos para realizar operaciones de entrada/salida en el sistema de archivos debido a la falta de recursos de E/S disponibles. Una presión alta de E/S puede indicar que el sistema está experimentando cuellos de botella en el acceso al disco o que hay un gran número de operaciones de E/S en espera.\n",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_pressure_cpu_waiting_seconds_total[$__rate_interval])",
     "legendFormat": "CPU"
    },
    {
     "expr": "irate(node_pressure_memory_waiting_seconds_total[$__rate_interval])",
     "legendFormat": "Mem"
    },
    {
     "expr": "irate(node_pressure_io_waiting_seconds_total[$__rate_interval])",
     "legendFormat": "I/O"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Sys Load",
   "type": "gauge",
   "description": "\"System load over all CPU cores together\" se refiere a la carga del sistema en todos los núcleos de la CPU combinados. La carga del sistema es una medida que indica la cantidad de trabajo que el sistema operativo está realizando en un momento dado. Esta carga se calcula teniendo en cuenta el número de procesos en ejecución o en espera para ejecutarse.\n\nCuando se habla de la carga del sistema en todos los núcleos de la CPU juntos, se está considerando la carga promedio en todas las CPU disponibles en el sistema. Esto es importante para comprender cómo se está utilizando la capacidad de procesamiento del sistema en su conjunto.\n\nUna carga alta del sistema puede indicar que hay una gran cantidad de procesos en ejecución o en cola esperando para ser ejecutados, lo que puede resultar en una respuesta lenta del sistema. Por otro lado, una carga baja del sistema indica que hay pocos procesos en ejecución o en espera, lo que generalmente significa que el sistema está subutilizado y tiene capacidad para manejar más trabajo.\n\nMonitorear la carga del sistema en todos los núcleos de la CPU proporciona una visión general del rendimiento del sistema y puede ayudar a identificar posibles cuellos de botella o situaciones de sobrecarga que puedan requerir atención.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(node_load1) * 100 / count(count(node_cpu_seconds_total) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) / (node_memory_SwapTotal_bytes)) * 100"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "\"Used Root FS\" se refiere al sistema de archivos raíz (Root FS) y muestra la cantidad de espacio utilizado en ese sistema de archivos. El sistema de archivos raíz es el punto de partida para la estructura de archivos en un sistema operativo Linux y contiene todos los archivos y directorios fundamentales necesarios para arrancar y operar el sistema.\n\nEsta métrica indica cuánto espacio se ha utilizado en el sistema de archivos raíz en comparación con el espacio total disponible. Es importante monitorear esta métrica para asegurarse de que haya suficiente espacio disponible en el sistema de archivos raíz para evitar problemas de espacio en disco que puedan afectar el rendimiento del sistema.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device=~\"/dev/.*\", mountpoint=\"/host\"} * 100) / node_filesystem_size_bytes{device=~\"/dev/.*\", mountpoint=\"/host\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device=~\"/dev/.*\", mountpoint=\"/host\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_SwapTotal_bytes" }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "- **System**: Monitorea el tiempo que los procesos del sistema pasan en modo kernel frente al total de la CPU. Un alto porcentaje indica sobrecarga potencial del sistema operativo, afectando el rendimiento, mientras que un bajo porcentaje muestra un uso eficiente de la CPU por aplicaciones de usuario.\n\n- **User**: Refleja el tiempo de CPU usado por procesos de usuario en modo usuario. Un alto porcentaje señala un uso eficiente de la CPU para aplicaciones y servicios; un aumento repentino podría significar una sobrecarga y afectar el rendimiento.\n\n- **Nice**: Mide el tiempo en modo usuario de procesos con prioridad reducida. Un valor alto indica una gestión efectiva de prioridades, mejorando el rendimiento al dar más CPU a tareas críticas cuando es necesario.\n\n- **Iowait**: Indica el tiempo esperando por operaciones de entrada/salida. Un alto porcentaje puede mostrar cuellos de botella en I/O, sugiriendo problemas de rendimiento por lentitud en dispositivos de almacenamiento o alta carga de E/S.\n\n- **Irq**: Tiempo de CPU dedicado a manejar interrupciones externas. Un alto porcentaje puede reflejar una actividad intensa de interrupciones, lo que podría impactar el rendimiento general del sistema.\n\n- **Softirq**: Tiempo dedicado a manejar interrupciones de software. Un alto porcentaje indica una carga significativa de trabajo de software, lo cual puede afectar negativamente el rendimiento del sistema.\n\n- **Steal**: Muestra el tiempo que una CPU de VM está inactiva esperando por recursos del host en entornos virtualizados. Es crucial para entender cómo las demandas de otras VMs pueden afectar el rendimiento de una instancia.\n\n- **Idle**: Proporción de tiempo en que la CPU está inactiva, sin realizar tareas activas. Un alto porcentaje sugiere capacidad de procesamiento disponible, lo que puede ser ventajoso en entornos con cargas fluctuantes.\n",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"system\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total) by (cpu)))",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total) by (cpu)))",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"nice\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total) by (cpu)))",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"iowait\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total) by (cpu)))",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"irq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total) by (cpu)))",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"softirq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total) by (cpu)))",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"steal\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total) by (cpu)))",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total) by (cpu)))",
     "legendFormat": "Idle - Waiting for something to happen"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "timeseries",
   "description": "- **Apps**: Muestra la memoria usada por aplicaciones en espacio de usuario, indicando el consumo de procesos de usuario en comparación con otras funciones del sistema como la caché.\n\n- **PageTables**: Memoria usada para las tablas de páginas, que son cruciales para mapear direcciones virtuales a físicas, facilitando el acceso a datos en la RAM.\n\n- **SwapCache**: Memoria que rastrea páginas traídas del swap y aún no modificadas. Alto uso puede indicar rendimiento subóptimo si la memoria principal está saturada.\n\n- **Slab**: Memoria que el kernel utiliza para caché de estructuras de datos como inodos y dentry. Alto uso sugiere acceso frecuente a estas estructuras, lo cual es positivo si hay suficiente memoria para mantenerlas en caché.\n\n- **Cache**: Memoria usada para la caché de archivos, almacenando datos leídos del disco. Un uso alto mejora la eficiencia al permitir accesos más rápidos a estos datos.\n\n- **Buffers**: Memoria para caché de datos de dispositivos de bloque como discos duros, lo que acelera el acceso a datos frecuentemente solicitados y evita accesos repetidos al disco.\n\n- **Unused**: Refleja la memoria libre y no asignada en el sistema, importante para evaluar la disponibilidad de recursos y si la memoria satisface las demandas del sistema.\n\n- **Swap**: Cantidad de espacio de intercambio usado. Un uso elevado puede señalar una sobrecarga de memoria, indicando la necesidad de optimizar el rendimiento del sistema.\n\n- **Hardware Corrupted**: Cantidad de RAM identificada como corrupta o no funcional, esencial para detectar problemas de hardware que afectan la estabilidad y rendimiento del sistema.\n",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes - node_memory_Slab_bytes - node_memory_PageTables_bytes - node_memory_SwapCached_bytes",
     "legendFormat": "Apps - Memory used by user-space applications"
    },
    {
     "expr": "node_memory_PageTables_bytes",
     "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
    },
    {
     "expr": "node_memory_SwapCached_bytes",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "node_memory_Slab_bytes",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
    },
    {
     "expr": "node_memory_Cached_bytes",
     "legendFormat": "Cache - Parked file data (file content) cache"
    },
    {
     "expr": "node_memory_Buffers_bytes",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "node_memory_MemFree_bytes",
     "legendFormat": "Unused - Free memory unassigned"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes)",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes",
     "legendFormat": "Hardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    }
   ]
  },
  {
   "title": "Network Traffic by Packets",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total[$__rate_interval])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_packets_total[$__rate_interval])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device=~\"/dev/.*\", mountpoint=\"/host\"} - node_filesystem_avail_bytes{device=~\"/dev/.*\", mountpoint=\"/host\"}",
     "legendFormat": "Disk Spaced Used: {{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{device=~\"/dev/.*\", mountpoint=\"/host\"}",
     "legendFormat": " Disk Size: {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Hardware temperature monitor",
   "type": "timeseries",
   "description": "- Calcula el promedio de las temperaturas medidas por los sensores de temperatura (en grados Celsius) agrupadas por el nombre del chip del hardware. \n\n- Recupera la información sobre alarmas de temperatura crítica (en grados Celsius) de los sensores de temperatura del hardware.",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by (chip) (node_hwmon_temp_celsius{chip=~\"thermal.*|platform.*\"})",
     "legendFormat": "{{chip}}"
    },
    {
     "expr": "node_hwmon_temp_crit_alarm_celsius{chip=~\"thermal.*|platform.*\"}",
     "legendFormat": "Alert: {{chip}}"
    }
   ]
  },
  {
   "title": "Node Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Node Exporter Scrape Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node_scrape_collector_duration_seconds",
       "legendFormat": "{{collector}} - Scrape duration"
      }
     ]
    },
    {
     "title": "Node Exporter Scrape",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "node_scrape_collector_success", "legendFormat": "{{collector}} - Scrape success" },
      {
       "expr": "node_textfile_scrape_error",
       "legendFormat": "{{collector}} - Scrape textfile error (1 = true)"
      }
     ]
    }
   ]
  }
 ]
}