# YAML Anchors for common configurations
x-common-build: &common-build
  context: ./app
  dockerfile: Dockerfile

x-common-depends_on_postgres: &common-depends_on_postgres
  postgres_db:
    condition: service_healthy

services:
  postgres_db:
    image: postgres:16
    container_name: postgres_db_container_bp
    env_file:
      - ./app/.env
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - dev
      - test
      - prod

  fastapi_app:
    build: *common-build
    container_name: fastapi_app_container_bp
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/app
      - ./volumes/fastapi_app_data:/app_data
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env
    depends_on: *common-depends_on_postgres
    profiles:
      - prod

  fastapi_app_dev:
    build: *common-build
    container_name: fastapi_app_dev_container_bp
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app
      - ./volumes/fastapi_app_data:/app_data
    ports:
      - "8001:8000"
    env_file:
      - ./app/.env
    depends_on: *common-depends_on_postgres
    profiles:
      - dev

  test_runner:
    build: *common-build
    container_name: test_runner_container_bp
    command: ["pytest", "/app/tests"]
    volumes:
      - ./app:/app
    env_file:
      - ./app/.env
    depends_on: *common-depends_on_postgres
    environment:
      PYTHONUNBUFFERED: "1"
    profiles:
      - test

volumes:
  postgres_data_bp:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PWD}/volumes/postgres_data'
  fastapi_app_data_bp:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PWD}/volumes/fastapi_app_data'
