apiVersion: 1
contactPoints:
    - orgId: 1
      name: grafana-provisioning-email
      receivers:
        - uid: ddkh09l7od24gb
          type: email
          settings:
            addresses: |
                $GRAFANA_EMAILS_TO_NOTIFY
            singleEmail: false
          disableResolveMessage: false

policies:
  - orgId: 1
    receiver: grafana-provisioning-email
