apiVersion: 1

datasources:
  - name: $PROMETHEUS_NAME_DATASOURCE
    type: prometheus
    access: proxy
    url: http://prometheus:$PROMETHEUS_PORT
    editable: true
    jsonData:
      timeInterval: $PROMETHEUS_TIME_SCRAP
    uid: uid-$PROMETHEUS_NAME_DATASOURCE